stages:
  - test
  - code-quality

services:
  - mysql:5.7
  - name: elasticsearch:7.2.0
    command: ["bin/elasticsearch", "-Ediscovery.type=single-node"]

variables:
  MYSQL_RANDOM_ROOT_PASSWORD: "yes"
  MYSQL_HOST: mysql
  MYSQL_DATABASE: bitrix
  MYSQL_USER: bitrix
  MYSQL_PASSWORD: bitrix
  ELASTICSEARCH_HOSTS: http://elasticsearch:9200

before_script:
  - apt-get update -yqq && apt-get install -yqq git zip unzip
  - docker-php-ext-install mysqli
  - pecl install xdebug
  - docker-php-ext-enable xdebug
  - curl -L https://getcomposer.org/installer | php --
  - php composer.phar install --no-interaction --prefer-dist
  - echo 'short_open_tag=1' >> $PHP_INI_DIR/php.ini
  - echo 'mbstring.func_overload=2' >> $PHP_INI_DIR/php.ini

PHP 7.1 / Bitrix 18.5:
  stage: test
  image: php:7.1
  script:
    - php composer.phar require --no-interaction --prefer-dist --dev sheerockoff/bitrix-ci:v18.5
    - vendor/bin/phpunit --whitelist src/ --coverage-text

PHP 7.1 / Bitrix 19.0:
  stage: test
  image: php:7.1
  script:
    - php composer.phar require --no-interaction --prefer-dist --dev sheerockoff/bitrix-ci:v19.0
    - vendor/bin/phpunit --whitelist src/ --coverage-text

PHP 7.2 / Bitrix 18.5:
  stage: test
  image: php:7.2
  script:
    - php composer.phar require --no-interaction --prefer-dist --dev sheerockoff/bitrix-ci:v18.5
    - vendor/bin/phpunit --whitelist src/ --coverage-text

PHP 7.2 / Bitrix 19.0:
  stage: test
  image: php:7.2
  script:
    - php composer.phar require --no-interaction --prefer-dist --dev sheerockoff/bitrix-ci:v19.0
    - vendor/bin/phpunit --whitelist src/ --coverage-text

PHP 7.3 / Bitrix 18.5:
  stage: test
  image: php:7.3
  script:
    - php composer.phar require --no-interaction --prefer-dist --dev sheerockoff/bitrix-ci:v18.5
    - vendor/bin/phpunit --whitelist src/ --coverage-text

PHP 7.3 / Bitrix 19.0:
  stage: test
  image: php:7.3
  script:
    - php composer.phar require --no-interaction --prefer-dist --dev sheerockoff/bitrix-ci:v19.0
    - vendor/bin/phpunit --whitelist src/ --coverage-text --coverage-clover clover.xml
  artifacts:
    paths:
      - clover.xml

Code Climate:
  stage: code-quality
  when: on_success
  allow_failure: true
  dependencies:
    - PHP 7.3 / Bitrix 19.0
  image: php:7.3
  before_script:
    - apt-get update -yqq && apt-get install -yqq git
    - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 --output code-climate
    - chmod +x code-climate
  script: ./code-climate after-build -t clover
