name: CodeClimate
on:
  push:
    branches:
      - master
jobs:
  CodeClimate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Install dependencies
        run: docker-compose run -T bitrix composer install --no-ansi --no-interaction --no-suggest --no-progress --prefer-dist

      - name: Run PHPUnit coverage test
        continue-on-error: true
        run: docker-compose run -T bitrix vendor/bin/phpunit --whitelist src/ --coverage-text --coverage-clover clover.xml

      - name: Push data to https://codeclimate.com
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 --output code-climate
          docker-compose run -T bitrix chmod +x code-climate
          docker-compose run -T bitrix ./code-climate after-build -t clover -r ${{ secrets.CC_TEST_REPORTER_ID }}